import React, { createContext, useContext, useState, useEffect } from 'react';

export type Theme = 'light' | 'dark';
export type Language = 'en' | 'es' | 'hi' | 'fr' | 'zh' | 'de' | 'te' | 'ar' | 'ja' | 'pt';

interface ThemeContextType {
  theme: Theme;
  toggleTheme: () => void;
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
  isTtsEnabled: boolean;
  toggleTts: () => void;
  speakText: (text: string) => void;
}

export const languagesList: { code: Language; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'hi', label: 'हिन्दी', flag: '🇮🇳' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'te', label: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
  { code: 'pt', label: 'Português', flag: '🇧🇷' },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    startChat: 'Start Chat',
    exploreDiseases: 'Explore Diseases',
    navHome: 'Home',
    navFeatures: 'Features',
    navDiseases: 'Diseases',
    navTips: 'Health Guides',
    navChatbot: 'Chatbot',
    navFAQ: 'Mostly Asked Questions',
    navContact: 'Contact',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    myHistory: 'My Chat History',
    guestUser: 'Guest User',
    selectLanguage: 'Select Language',
    symptomCheckBtn: 'Symptom Triage',

    newChat: 'New chat',
    textToSpeech: 'Text-to-Speech',
    navImages: 'Images',
    recents: 'Recents',
    viewAll: 'View All',
    connectedAs: 'Connected as',
    verifiedRepo: 'WHO & CDC Verified Knowledge Base',
    whereToBegin: 'Where should we begin?',
    heroCanvasSubtitle: 'Ask HealthAI about symptoms, disease prevention, vaccination guidelines, or regional public health safety.',
    askAnything: 'Ask anything...',
    createAnImage: 'Create an image',
    visualDiseaseGuide: 'Visual Disease Guide',
    writeOrEdit: 'Write or edit',
    healthGuidelines: 'Health Guidelines',
    searchTheWeb: 'Search the web',
    publicHealthRepo: 'Public Health Repo',
    welcomeMessage: 'Hello! I am HealthAI, your 24/7 Public Health Assistant. Ask me about disease symptoms, preventive guidelines, vaccination schedules, or health tips.',

    // Hero
    heroTag: '24/7 AI Public Health Platform',
    heroTitle: 'AI-Driven Public Health Chatbot for Disease Awareness',
    heroSubtitle: 'Empowering communities with AI-powered health guidance, disease awareness, preventive care, and trusted public health information—available anytime, anywhere.',
    activeUsers: 'Active Users Guarded',
    verifiedArticles: 'Clinical Sources Verified',
    instantAnswers: '24/7 AI Health Support',
    heroBadge: 'Empowering Preventive Care',

    // How It Works
    howItWorksTag: 'Seamless Workflow',
    howItWorksTitle: 'How HealthAI Works in 4 Steps',
    howItWorksSubtitle: 'From query to evidence-based advice in seconds—designed for speed, simplicity, and clinical trust.',
    step1Title: 'Ask a Health Question',
    step1Desc: 'Type or speak your symptoms, disease queries, or prevention questions in plain natural language.',
    step1Tag: 'Step 1: Input',
    step2Title: 'AI Analyzes Query',
    step2Desc: 'Our specialized medical language model evaluates keywords, symptom intensity, and clinical severity markers.',
    step2Tag: 'Step 2: Processing',
    step3Title: 'Retrieves Trusted Info',
    step3Desc: 'Cross-references evidence-based public health datasets from WHO, CDC, and verified medical literature.',
    step3Tag: 'Step 3: Verification',
    step4Title: 'Actionable Guidance',
    step4Desc: 'Delivers clear preventive steps, symptom triage level, and immediate care recommendations.',
    step4Tag: 'Step 4: Output',

    // Statistics
    statsTag: 'Measurable Public Impact',
    statsTitle: 'Trusted Global Health Data at Scale',
    statsSubtitle: 'Real-time metrics demonstrating our commitment to public health literacy and early intervention.',
    stat1Value: '100,000+',
    stat1Label: 'Individuals Assisted',
    stat1Desc: 'Empowered with immediate preventive guidance across 40+ countries.',
    stat2Value: '50+',
    stat2Label: 'Diseases Indexed',
    stat2Desc: 'Comprehensive coverage of infectious and chronic health conditions.',
    stat3Value: '99.4%',
    stat3Label: 'Clinical Accuracy',
    stat3Desc: 'Validated against World Health Organization clinical triage standards.',
    stat4Value: '24/7',
    stat4Label: 'Instant Support',
    stat4Desc: 'Zero wait time with instant natural language processing.',

    // Why Choose Us
    whyTag: 'Built for Public Impact',
    whyTitle: 'Why Communities Trust HealthAI',
    whySubtitle: 'Combining state-of-the-art AI technology with verified epidemiological standards.',
    why1Title: 'Evidence-Based Medical Engine',
    why1Desc: 'All responses are cross-checked against guidelines from the WHO and CDC.',
    why2Title: 'Privacy-First Architecture',
    why2Desc: 'We enforce zero-retention data policies. Your queries remain anonymous.',
    why3Title: 'Multilingual Inclusivity',
    why3Desc: 'Breaking language barriers with instant translations in 10 major global languages.',
    why4Title: 'Empathetic & Accessible',
    why4Desc: 'Simple UI designed for users of all digital literacy levels.',

    // Features Section
    featuresTag: 'Comprehensive Capability',
    featuresTitle: 'Engineered for Modern Public Healthcare',
    featuresSubtitle: 'Discover powerful AI-driven features designed to educate, guide, and safeguard individuals.',
    filterAll: 'All Features (10)',
    filterAI: 'AI Focus',
    filterPrevention: 'Prevention Focus',
    filterSecurity: 'Security Focus',
    searchFeaturesPlaceholder: 'Search features...',
    verifiedCapability: 'Verified Capability',
    launchTool: 'Launch Interactive Tool',

    // Diseases Section
    diseasesTag: 'Public Health Database',
    diseasesTitle: 'Disease Awareness & Prevention Hub',
    diseasesSubtitle: 'Explore verified symptoms, root causes, transmission modes, and prevention strategies.',
    searchDiseasesPlaceholder: 'Search diseases by name, symptom, or cause...',
    allCategories: 'All Categories',
    symptomsLabel: 'Key Symptoms:',
    preventionLabel: 'Prevention Strategy:',
    learnDetails: 'Learn Prevention & Details',
    icdCodeLabel: 'ICD Code',
    transmissionLabel: 'Transmission Mode',
    symptomsHeader: 'Clinical Symptoms',
    causesHeader: 'Etiology & Causes',
    preventionHeader: 'Preventive Protocol',
    emergencyHeader: 'Red-Flag Emergency Warning:',
    shareGuide: 'Share Guide',
    closeProfile: 'Close Profile',

    // Health Tips Section
    tipsTag: 'Daily Wellness',
    tipsTitle: 'Daily Health & Wellness Tips',
    tipsSubtitle: 'Evidence-based recommendations for maintaining peak immune function and longevity.',
    bookmark: 'Bookmark',
    bookmarked: 'Bookmarked',

    // Chatbot Section
    chatbotTitle: '24×7 HealthAI Assistant',
    chatbotSubtitle: 'Ask any health query in natural language to receive verified preventive care guidance.',
    chatbotHeaderTitle: 'HealthAI Assistant',
    chatbotHeaderStatus: 'Online',
    chatPlaceholder: 'Ask HealthAI a question (e.g. How to prevent dengue fever?)...',
    send: 'Send',
    clearChat: 'Clear Chat',
    exportChat: 'Export Chat',
    historyBtn: 'Chat History',
    disclaimer: 'Disclaimer: HealthAI provides educational insights based on public health data. Always seek professional emergency care for severe conditions.',
    samplePromptTitle: 'Suggested Questions:',

    // FAQ Section
    faqTag: 'Knowledge Base',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Find quick answers regarding our medical AI platform, privacy, and clinical accuracy.',
    faqQ1: 'Is this chatbot a replacement for professional medical advice or doctors?',
    faqA1: 'No. HealthAI is an educational public health tool designed for awareness and preventive guidance. In case of acute symptoms, consult a licensed physician immediately.',
    faqQ2: 'Is my health information private and secure when asking questions?',
    faqA2: 'Yes, 100%. We employ zero-retention data policies. All interaction traffic is encrypted using AES-256 standards.',
    faqQ3: 'Which public health diseases and conditions are covered in HealthAI?',
    faqA3: 'HealthAI covers over 50+ communicable and chronic diseases including Dengue, Malaria, COVID-19, Diabetes, Tuberculosis, and Typhoid.',
    faqQ4: 'Is HealthAI available 24 hours a day, 7 days a week?',
    faqA4: 'Yes! HealthAI operates continuously 24/7 on high-availability infrastructure so you can access health info anytime.',
    faqQ5: 'Can I use HealthAI on my mobile smartphone or tablet?',
    faqA5: 'Yes. HealthAI is built as a progressive, mobile-first web app that works seamlessly on iOS, Android, and desktops.',
    faqQ6: 'Where does HealthAI source its health and disease prevention information?',
    faqA6: 'Our knowledge bases are synthesized from public health guidelines issued by global authorities including the WHO and CDC.',

    // Contact Section
    contactTag: 'Connect With Us',
    contactTitle: 'Get in Touch with HealthAI',
    contactSubtitle: 'Have feedback, questions, or partnership inquiries? Reach out to our technical team.',
    nameField: 'Full Name',
    emailField: 'Email Address',
    messageField: 'Your Message',
    sendMessage: 'Send Message',
    contactAddressLabel: 'Headquarters',
    contactPhoneLabel: '24/7 Helpline',
    contactEmailUsLabel: 'Official Email',

    // Footer & Modals
    copyright: '© 2026 HealthAI Public Health Platform. All rights reserved.',
    authTitle: 'Welcome to HealthAI',
    authSubtitle: 'Sign in to save your health queries and search history across devices.',
    loginTab: 'Sign In',
    registerTab: 'Create Account',
    googleBtn: 'Continue with Google',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    nameLabel: 'Full Name',
    alreadyAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    historyTitle: 'Your Search & Chat History',
    historySubtitle: 'Review past health queries, risk evaluations, and AI answers.',
    noHistory: 'No past search history found.',
    clearHistoryBtn: 'Clear All History',
    reloadQuery: 'Reload in Chat',
    riskLow: 'Low Risk',
    riskModerate: 'Moderate Risk',
    riskUrgent: 'Urgent Attention',

    // Symptom Modal
    symptomModalTitle: 'Interactive Symptom Checker & Triage',
    symptomModalSubtitle: 'Select your experienced symptoms below to receive an instant clinical risk triage evaluation.',
    evaluateBtn: 'Evaluate Risk Level',
    resetBtn: 'Reset Selection'
  },

  es: {
    startChat: 'Iniciar Chat',
    exploreDiseases: 'Explorar Enfermedades',
    navHome: 'Inicio',
    navFeatures: 'Características',
    navDiseases: 'Enfermedades',
    navTips: 'Consejos de Salud',
    navChatbot: 'Chatbot AI',
    navFAQ: 'Preguntas',
    navContact: 'Contacto',
    signIn: 'Iniciar Sesión',
    signOut: 'Cerrar Sesión',
    myHistory: 'Mi Historial de Chat',
    guestUser: 'Usuario Invitado',
    selectLanguage: 'Seleccionar Idioma',
    symptomCheckBtn: 'Chequeo de Síntomas',

    heroTag: 'Plataforma de Salud Pública IA 24/7',
    heroTitle: 'Chatbot de Salud Pública con IA para Concientización',
    heroSubtitle: 'Empoderando comunidades con orientación médica por IA, prevención de enfermedades e información confiable disponible en cualquier momento.',
    activeUsers: 'Usuarios Activos Protegidos',
    verifiedArticles: 'Fuentes Clínicas Verificadas',
    instantAnswers: 'Soporte de Salud IA 24/7',
    heroBadge: 'Promoviendo la Atención Preventiva',

    howItWorksTag: 'Flujo Simplificado',
    howItWorksTitle: 'Cómo Funciona HealthAI en 4 Pasos',
    howItWorksSubtitle: 'Desde su consulta hasta recomendaciones médicas en segundos.',
    step1Title: 'Realice una Consulta',
    step1Desc: 'Escriba sus síntomas o preguntas sobre enfermedades en lenguaje natural.',
    step1Tag: 'Paso 1: Entrada',
    step2Title: 'Análisis de la IA',
    step2Desc: 'Nuestro modelo médico evalúa palabras clave y severidad clínica.',
    step2Tag: 'Paso 2: Procesamiento',
    step3Title: 'Búsqueda Verificada',
    step3Desc: 'Contrasta información con bases de datos públicas de la OMS y los CDC.',
    step3Tag: 'Paso 3: Verificación',
    step4Title: 'Guía Práctica',
    step4Desc: 'Entrega recomendaciones claras de prevención y nivel de riesgo.',
    step4Tag: 'Paso 4: Resultado',

    statsTag: 'Impacto Público Medible',
    statsTitle: 'Datos de Salud Global a Gran Escala',
    statsSubtitle: 'Métricas en tiempo real sobre nuestro compromiso con la salud pública.',
    stat1Value: '100,000+',
    stat1Label: 'Personas Atendidas',
    stat1Desc: 'Con orientación preventiva inmediata en más de 40 países.',
    stat2Value: '50+',
    stat2Label: 'Enfermedades Catalogadas',
    stat2Desc: 'Cobertura de condiciones infecciosas y crónicas.',
    stat3Value: '99.4%',
    stat3Label: 'Precisión Clínica',
    stat3Desc: 'Validado con estándares de triaje de la OMS.',
    stat4Value: '24/7',
    stat4Label: 'Atención Inmediata',
    stat4Desc: 'Sin tiempos de espera con procesamiento automático.',

    whyTag: 'Diseñado para Impacto Social',
    whyTitle: 'Por qué las Comunidades Confían en HealthAI',
    whySubtitle: 'Uniendo tecnología de IA avanzada con estándares epidemiológicos.',
    why1Title: 'Motor Basado en Evidencia',
    why1Desc: 'Respuestas respaldadas por la OMS y los CDC.',
    why2Title: 'Privacidad Garantizada',
    why2Desc: 'No almacenamos sus datos identificables. Consultas anónimas.',
    why3Title: 'Inclusión Multilingüe',
    why3Desc: 'Traducciones al instante en 10 idiomas globales.',
    why4Title: 'Accesible y Empático',
    why4Desc: 'Interfaz sencilla apta para cualquier usuario.',

    featuresTag: 'Capacidad Integral',
    featuresTitle: 'Diseñado para la Salud Pública Moderna',
    featuresSubtitle: 'Descubra potentes funciones impulsadas por IA para orientar y proteger.',
    filterAll: 'Todas las Funciones (10)',
    filterAI: 'Enfoque IA',
    filterPrevention: 'Enfoque Prevención',
    filterSecurity: 'Enfoque Seguridad',
    searchFeaturesPlaceholder: 'Buscar características...',
    verifiedCapability: 'Capacidad Verificada',
    launchTool: 'Abrir Herramienta',

    diseasesTag: 'Base de Datos Médica',
    diseasesTitle: 'Centro de Prevención de Enfermedades',
    diseasesSubtitle: 'Consulte síntomas, causas y estrategias de prevención verificadas.',
    searchDiseasesPlaceholder: 'Buscar por nombre, síntoma o causa...',
    allCategories: 'Todas las Categorías',
    symptomsLabel: 'Síntomas Principales:',
    preventionLabel: 'Estrategia de Prevención:',
    learnDetails: 'Ver Detalle y Prevención',
    icdCodeLabel: 'Código CIE',
    transmissionLabel: 'Modo de Transmisión',
    symptomsHeader: 'Síntomas Clínicos',
    causesHeader: 'Causas y Etiología',
    preventionHeader: 'Protocolo Preventivo',
    emergencyHeader: 'Alerta de Emergencia:',
    shareGuide: 'Compartir Guía',
    closeProfile: 'Cerrar Ficha',

    tipsTag: 'Bienestar Diario',
    tipsTitle: 'Consejos Diarios de Salud y Bienestar',
    tipsSubtitle: 'Recomendaciones para mantener un sistema inmunológico fuerte.',
    bookmark: 'Guardar',
    bookmarked: 'Guardado',

    chatbotTitle: 'Asistente de Salud IA 24/7',
    chatbotSubtitle: 'Haga cualquier consulta de salud en lenguaje natural para recibir orientación médica.',
    chatbotHeaderTitle: 'Asistente HealthAI',
    chatbotHeaderStatus: 'En Línea',
    chatPlaceholder: 'Escriba su consulta médica (ej. ¿Cómo prevenir el dengue?)...',
    send: 'Enviar',
    clearChat: 'Borrar Chat',
    exportChat: 'Exportar Chat',
    historyBtn: 'Historial',
    disclaimer: 'Aviso: HealthAI brinda información educativa. Ante emergencias médicas, acuda al hospital.',
    samplePromptTitle: 'Preguntas Sugeridas:',

    faqTag: 'Base de Conocimiento',
    faqTitle: 'Preguntas Frecuentes',
    faqSubtitle: 'Respuestas rápidas sobre nuestra plataforma médica y seguridad.',
    faqQ1: '¿Este chatbot reemplaza la consulta con un médico profesional?',
    faqA1: 'No. HealthAI es una herramienta educativa de salud pública. Ante síntomas graves, consulte con un médico de inmediato.',
    faqQ2: '¿Mi información de salud es privada y confidencial?',
    faqA2: 'Sí, 100%. Aplicamos políticas de cero retención de datos personales.',
    faqQ3: '¿Qué enfermedades están incluidas en HealthAI?',
    faqA3: 'Incluye más de 50 condiciones como Dengue, Malaria, COVID-19, Diabetes, Tuberculosis y Fiebre Tifoidea.',
    faqQ4: '¿HealthAI está disponible las 24 horas del día?',
    faqA4: 'Sí, la plataforma opera 24/7 de forma ininterrumpida.',
    faqQ5: '¿Puedo usar HealthAI en teléfonos inteligentes?',
    faqA5: 'Sí, funciona perfectamente en iOS, Android y ordenadores.',
    faqQ6: '¿De dónde obtiene HealthAI su información médica?',
    faqA6: 'Se sintetiza a partir de pautas de la Organización Mundial de la Salud (OMS) y los CDC.',

    contactTag: 'Contacto',
    contactTitle: 'Póngase en Contacto con HealthAI',
    contactSubtitle: '¿Tiene preguntas o sugerencias? Escriba a nuestro equipo técnico.',
    nameField: 'Nombre Completo',
    emailField: 'Correo Electrónico',
    messageField: 'Su Mensaje',
    sendMessage: 'Enviar Mensaje',
    contactAddressLabel: 'Sede Principal',
    contactPhoneLabel: 'Línea 24/7',
    contactEmailUsLabel: 'Correo Oficial',

    copyright: '© 2026 Plataforma de Salud Pública HealthAI. Todos los derechos reservados.',
    authTitle: 'Bienvenido a HealthAI',
    authSubtitle: 'Inicie sesión para guardar sus consultas e historial en todos sus dispositivos.',
    loginTab: 'Iniciar Sesión',
    registerTab: 'Crear Cuenta',
    googleBtn: 'Continuar con Google',
    emailLabel: 'Correo Electrónico',
    passwordLabel: 'Contraseña',
    nameLabel: 'Nombre Completo',
    alreadyAccount: '¿Ya tienes una cuenta?',
    noAccount: '¿No tienes una cuenta?',
    historyTitle: 'Tu Historial de Búsquedas y Chat',
    historySubtitle: 'Revisa tus consultas pasadas y respuestas de la IA.',
    noHistory: 'No se encontró historial previo.',
    clearHistoryBtn: 'Borrar Todo el Historial',
    reloadQuery: 'Recargar en el Chat',
    riskLow: 'Riesgo Bajo',
    riskModerate: 'Riesgo Moderado',
    riskUrgent: 'Atención Urgente',

    symptomModalTitle: 'Evaluador de Síntomas y Triaje',
    symptomModalSubtitle: 'Seleccione sus síntomas para recibir un análisis de riesgo en tiempo real.',
    evaluateBtn: 'Evaluar Nivel de Riesgo',
    resetBtn: 'Reiniciar Selección'
  },

  hi: {
    startChat: 'चैट शुरू करें',
    exploreDiseases: 'बीमारियों को देखें',
    navHome: 'होम',
    navFeatures: 'विशेषताएं',
    navDiseases: 'बीमारियां',
    navTips: 'स्वास्थ्य सुझाव',
    navChatbot: 'एआई बॉट',
    navFAQ: 'सवाल-जवाब',
    navContact: 'संपर्क करें',
    signIn: 'साइन इन करें',
    signOut: 'साइन आउट',
    myHistory: 'चैट इतिहास',
    guestUser: 'अतिथि उपयोगकर्ता',
    selectLanguage: 'भाषा चुनें',
    symptomCheckBtn: 'लक्षण जांचें',

    heroTag: '24/7 एआई जन स्वास्थ्य मंच',
    heroTitle: 'रोग जागरूकता के लिए एआई-संचालित जन स्वास्थ्य चैटबॉट',
    heroSubtitle: 'एआई-संचालित स्वास्थ्य मार्गदर्शन, बीमारी जागरूकता, निवारक देखभाल और विश्वसनीय स्वास्थ्य जानकारी से समुदायों को सशक्त बनाना।',
    activeUsers: 'सुरक्षित सक्रिय उपयोगकर्ता',
    verifiedArticles: 'सत्यापित चिकित्सकीय स्रोत',
    instantAnswers: '24/7 एआई स्वास्थ्य सहायता',
    heroBadge: 'निवारक देखभाल को बढ़ावा',

    howItWorksTag: 'सरल प्रक्रिया',
    howItWorksTitle: 'हेल्थ-एआई 4 आसान चरणों में कैसे काम करता है',
    howItWorksSubtitle: 'आपके प्रश्न से लेकर सत्यापित चिकित्सा सलाह तक सेकंडों में पहुंचें।',
    step1Title: 'स्वास्थ्य प्रश्न पूछें',
    step1Desc: 'अपने लक्षण या बीमारी से जुड़े सवाल अपनी भाषा में टाइप करें या बोलें।',
    step1Tag: 'चरण 1: इनपुट',
    step2Title: 'एआई विश्लेषण करता है',
    step2Desc: 'हमारा मेडिकल एआई मॉडल मुख्य शब्दों और गंभीरता का विश्लेषण करता है।',
    step2Tag: 'चरण 2: प्रोसेसिंग',
    step3Title: 'सत्यापित जानकारी लाता है',
    step3Desc: 'विश्व स्वास्थ्य संगठन (WHO) और CDC डेटाबेस से मिलान करता है।',
    step3Tag: 'चरण 3: सत्यापन',
    step4Title: 'सटीक मार्गदर्शन',
    step4Desc: 'स्पष्ट निवारक उपाय और जोखिम स्तर की जानकारी देता है।',
    step4Tag: 'चरण 4: परिणाम',

    statsTag: 'मापने योग्य प्रभाव',
    statsTitle: 'वैश्विक स्वास्थ्य डेटा और जन सेवा',
    statsSubtitle: 'सार्वजनिक स्वास्थ्य जागरूकता के प्रति हमारी प्रतिबद्धता।',
    stat1Value: '100,000+',
    stat1Label: 'मदद प्राप्त नागरिक',
    stat1Desc: '40 से अधिक देशों में तुरंत स्वास्थ्य सहायता प्रदान की गई।',
    stat2Value: '50+',
    stat2Label: 'सूचीबद्ध बीमारियां',
    stat2Desc: 'संक्रामक और पुरानी बीमारियों की विस्तृत जानकारी।',
    stat3Value: '99.4%',
    stat3Label: 'चिकित्सकीय सटीकता',
    stat3Desc: 'WHO स्वास्थ्य मानकों के अनुरूप।',
    stat4Value: '24/7',
    stat4Label: 'तुरंत सहायता',
    stat4Desc: 'बिना किसी इंतजार के तुरंत जवाब।',

    whyTag: 'जनहित के लिए निर्मित',
    whyTitle: 'लोग हेल्थ-एआई पर भरोसा क्यों करते हैं',
    whySubtitle: 'एआई तकनीक और स्थापित चिकित्सा मानकों का अनूठा मेल।',
    why1Title: 'साक्ष्य-आधारित इंजन',
    why1Desc: 'सभी उत्तर WHO और CDC दिशा-निर्देशों से सत्यापित हैं।',
    why2Title: 'पूर्ण गोपनीयता',
    why2Desc: 'आपकी जानकारी पूरी तरह सुरक्षित और गुप्त रहती है।',
    why3Title: 'बहुभाषी सहायता',
    why3Desc: '10 प्रमुख भाषाओं में तुरंत अनुवाद।',
    why4Title: 'आसान और सुलभ',
    why4Desc: 'सरल इंटरफेस जिसे कोई भी आसानी से उपयोग कर सकता है।',

    featuresTag: 'उन्नत क्षमताएं',
    featuresTitle: 'आधुनिक जन स्वास्थ्य के लिए तैयार',
    featuresSubtitle: 'आपकी सुरक्षा और जागरूकता के लिए एआई सुविधाएं।',
    filterAll: 'सभी विशेषताएं (10)',
    filterAI: 'एआई फोकस',
    filterPrevention: 'बचाव फोकस',
    filterSecurity: 'सुरक्षा फोकस',
    searchFeaturesPlaceholder: 'सुविधाएं खोजें...',
    verifiedCapability: 'सत्यापित क्षमता',
    launchTool: 'टूूल चालू करें',

    diseasesTag: 'रोग डेटाबेस',
    diseasesTitle: 'बीमारी जागरूकता एवं रोकथाम केंद्र',
    diseasesSubtitle: 'लक्षणों, कारणों और बचाव के तरीकों की पूरी जानकारी पाएं।',
    searchDiseasesPlaceholder: 'बीमारी, लक्षण या कारण खोजें...',
    allCategories: 'सभी श्रेणियां',
    symptomsLabel: 'मुख्य लक्षण:',
    preventionLabel: 'बचाव के उपाय:',
    learnDetails: 'बचाव और विवरण देखें',
    icdCodeLabel: 'ICD कोड',
    transmissionLabel: 'फैलने का तरीका',
    symptomsHeader: 'नैदानिक लक्षण',
    causesHeader: 'कारण और उत्पत्ति',
    preventionHeader: 'निवारक नियम',
    emergencyHeader: 'आपत्कालीन चेतावनी:',
    shareGuide: 'शेयर करें',
    closeProfile: 'बंद करें',

    tipsTag: 'दैनिक स्वास्थ्य',
    tipsTitle: 'दैनिक स्वास्थ्य और कल्याण सुझाव',
    tipsSubtitle: 'प्रतिरक्षा प्रणाली को मजबूत रखने के लिए वैज्ञानिक सुझाव।',
    bookmark: 'सेव करें',
    bookmarked: 'सेव किया गया',

    chatbotTitle: '24×7 स्वास्थ्य एआई सहायक',
    chatbotSubtitle: 'सत्यापित निवारक देखभाल मार्गदर्शन प्राप्त करने के लिए कोई भी प्रश्न पूछें।',
    chatbotHeaderTitle: 'हेल्थ-एआई सहायक',
    chatbotHeaderStatus: 'ऑनलाइन',
    chatPlaceholder: 'स्वास्थ्य संबंधी सवाल पूछें (जैसे: डेंगू से कैसे बचें?)...',
    send: 'भेजें',
    clearChat: 'चैट साफ करें',
    exportChat: 'चैट डाउनलोड करें',
    historyBtn: 'इतिहास',
    disclaimer: 'अस्वीकरण: हेल्थ-एआई सार्वजनिक स्वास्थ्य डेटा के आधार पर जानकारी देता है। आपात स्थिति में डॉक्टर से मिलें।',
    samplePromptTitle: 'सुझाए गए प्रश्न:',

    faqTag: 'ज्ञान केंद्र',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    faqSubtitle: 'हमारे मेडिकल एआई और गोपनीयता से जुड़े त्वरित उत्तर।',
    faqQ1: 'क्या यह चैटबॉट डॉक्टर की सलाह की जगह ले सकता है?',
    faqA1: 'नहीं। यह एक जागरूकता और शिक्षा उपकरण है। गंभीर लक्षण होने पर तुरंत डॉक्टर को दिखाएं।',
    faqQ2: 'क्या मेरी स्वास्थ्य जानकारी गुप्त रहती है?',
    faqA2: 'जी हां, 100%। हम आपकी पहचान से जुड़ी जानकारी नहीं रखते।',
    faqQ3: 'इसमें कौन-कौन सी बीमारियों की जानकारी उपलब्ध है?',
    faqA3: 'डेंगू, मलेरिया, कोविड-19, डायबिटीज, टीबी और टाइफाइड सहित 50+ बीमारियां शामिल हैं।',
    faqQ4: 'क्या यह सुविधा 24 घंटे उपलब्ध है?',
    faqA4: 'हां, यह सेवा बिना रुके 24 घंटे और 7 दिन चालू रहती है।',
    faqQ5: 'क्या मैं इसे मोबाइल में इस्तेमाल कर सकता हूं?',
    faqA5: 'हां! यह मोबाइल, टैबलेट और कंप्यूटर सब पर आसानी से चलता है।',
    faqQ6: 'यह जानकारी कहां से ली गई है?',
    faqA6: 'विश्व स्वास्थ्य संगठन (WHO) और CDC के आधिकारिक दिशा-निर्देशों से।',

    contactTag: 'संपर्क करें',
    contactTitle: 'हेल्थ-एआई टीम से संपर्क करें',
    contactSubtitle: 'कोई सवाल या सुझाव है? हमारी टीम से संपर्क करें।',
    nameField: 'पूरा नाम',
    emailField: 'ईमेल पता',
    messageField: 'आपका संदेश',
    sendMessage: 'संदेश भेजें',
    contactAddressLabel: 'मुख्य कार्यालय',
    contactPhoneLabel: '24/7 हेल्पलाइन',
    contactEmailUsLabel: 'आधिकारिक ईमेल',

    copyright: '© 2026 हेल्थ-एआई जन स्वास्थ्य प्लेटफॉर्म। सर्वाधिकार सुरक्षित।',
    authTitle: 'हेल्थ-एआई में आपका स्वागत है',
    authSubtitle: 'अपने स्वास्थ्य प्रश्नों और इतिहास को सुरक्षित रखने के लिए साइन इन करें।',
    loginTab: 'साइन इन',
    registerTab: 'नया खाता बनाएं',
    googleBtn: 'गूगल से जारी रखें',
    emailLabel: 'ईमेल पता',
    passwordLabel: 'पासवर्ड',
    nameLabel: 'पूरा नाम',
    alreadyAccount: 'क्या आपके पास पहले से खाता है?',
    noAccount: 'खाता नहीं है?',
    historyTitle: 'आपकी खोज और चैट इतिहास',
    historySubtitle: 'अपने पिछले प्रश्नों और उत्तरों की समीक्षा करें।',
    noHistory: 'कोई पिछला इतिहास नहीं मिला।',
    clearHistoryBtn: 'सभी इतिहास हटाएं',
    reloadQuery: 'चैट में खोलें',
    riskLow: 'कम जोखिम',
    riskModerate: 'मध्यम जोखिम',
    riskUrgent: 'तत्काल ध्यान दें',

    symptomModalTitle: 'लक्षण जांच और जोखिम मूल्यांकन',
    symptomModalSubtitle: 'अपने लक्षण चुनें और तुरंत स्वास्थ्य जोखिम स्तर जांचें।',
    evaluateBtn: 'जोखिम जांचें',
    resetBtn: 'रीसेट करें'
  },

  fr: {
    startChat: 'Démarrer le Chat',
    exploreDiseases: 'Explorer les Maladies',
    navHome: 'Accueil',
    navFeatures: 'Fonctionnalités',
    navDiseases: 'Maladies',
    navTips: 'Conseils Santé',
    navChatbot: 'Chatbot IA',
    navFAQ: 'FAQ',
    navContact: 'Contact',
    signIn: 'Se Connecter',
    signOut: 'Se Déconnecter',
    myHistory: 'Historique des Chats',
    guestUser: 'Utilisateur Invité',
    selectLanguage: 'Sélectionner la Langue',
    symptomCheckBtn: 'Vérificateur de Symptômes',

    heroTag: 'Plateforme Santé Publique IA 24/7',
    heroTitle: 'Chatbot de Santé Publique Propulsé par IA',
    heroSubtitle: 'Autonomiser les communautés avec des conseils de santé alimentés par l\'IA et des informations de prévention fiables.',
    activeUsers: 'Utilisateurs Actifs Protégés',
    verifiedArticles: 'Sources Médicales Vérifiées',
    instantAnswers: 'Support Santé IA 24/7',
    heroBadge: 'Promouvoir les Soins Préventifs',

    howItWorksTag: 'Workflow Fluide',
    howItWorksTitle: 'Comment Fonctionne HealthAI en 4 Étapes',
    howItWorksSubtitle: 'De votre question à des conseils médicaux vérifiés en quelques secondes.',
    step1Title: 'Posez une Question',
    step1Desc: 'Saisissez vos symptômes ou questions de santé en langage naturel.',
    step1Tag: 'Étape 1: Saisie',
    step2Title: 'Analyse par l\'IA',
    step2Desc: 'Notre modèle médical évalue les mots-clés et le niveau de sévérité.',
    step2Tag: 'Étape 2: Traitement',
    step3Title: 'Vérification Médicale',
    step3Desc: 'Croise les données avec les bases de l\'OMS et des CDC.',
    step3Tag: 'Étape 3: Vérification',
    step4Title: 'Conseils Pratiques',
    step4Desc: 'Délivre des consignes de prévention claires et adaptées.',
    step4Tag: 'Étape 4: Résultat',

    statsTag: 'Impact Mesurable',
    statsTitle: 'Données de Santé Publique à Grande Échelle',
    statsSubtitle: 'Métriques en temps réel démontrant notre engagement.',
    stat1Value: '100,000+',
    stat1Label: 'Personnes Assistées',
    stat1Desc: 'Guidées dans plus de 40 pays.',
    stat2Value: '50+',
    stat2Label: 'Maladies Répertoriées',
    stat2Desc: 'Couverture complète des maladies infectieuses et chroniques.',
    stat3Value: '99.4%',
    stat3Label: 'Précision Clinique',
    stat3Desc: 'Conforme aux standards de triage de l\'OMS.',
    stat4Value: '24/7',
    stat4Label: 'Support Instantané',
    stat4Desc: 'Réponse immédiate sans attente.',

    whyTag: 'Conçu pour l\'Intérêt Général',
    whyTitle: 'Pourquoi les Communautés Font Confiance à HealthAI',
    whySubtitle: 'Alliant l\'IA avancée aux standards épidémiologiques.',
    why1Title: 'Moteur Basé sur les Preuves',
    why1Desc: 'Toutes les réponses sont vérifiées selon l\'OMS et les CDC.',
    why2Title: 'Respect de la Vie Privée',
    why2Desc: 'Aucune donnée personnelle n\'est conservée. Vos requêtes restent anonymes.',
    why3Title: 'Inclusion Multilingue',
    why3Desc: 'Traduction instantanée dans 10 langues mondiales.',
    why4Title: 'Accessible à Tous',
    why4Desc: 'Interface simple adaptée à tous les publics.',

    featuresTag: 'Capacités Complètes',
    featuresTitle: 'Conçu pour la Santé Publique Moderne',
    featuresSubtitle: 'Découvrez nos fonctionnalités basées sur l\'IA pour informer et protéger.',
    filterAll: 'Toutes (10)',
    filterAI: 'Focus IA',
    filterPrevention: 'Focus Prévention',
    filterSecurity: 'Focus Sécurité',
    searchFeaturesPlaceholder: 'Rechercher une fonctionnalité...',
    verifiedCapability: 'Capacité Vérifiée',
    launchTool: 'Lancer l\'Outil',

    diseasesTag: 'Base de Données Médicale',
    diseasesTitle: 'Centre d\'Information et Prévention des Maladies',
    diseasesSubtitle: 'Consultez les symptômes, causes et conseils de prévention.',
    searchDiseasesPlaceholder: 'Rechercher par nom, symptôme ou cause...',
    allCategories: 'Toutes les Catégories',
    symptomsLabel: 'Symptômes Clés:',
    preventionLabel: 'Stratégie de Prévention:',
    learnDetails: 'En Savoir Plus & Prévention',
    icdCodeLabel: 'Code CIM',
    transmissionLabel: 'Mode de Transmission',
    symptomsHeader: 'Symptômes Cliniques',
    causesHeader: 'Étiologie & Causes',
    preventionHeader: 'Protocole Préventif',
    emergencyHeader: 'Alerte Urgence:',
    shareGuide: 'Partager',
    closeProfile: 'Fermer',

    tipsTag: 'Bien-être Quotidien',
    tipsTitle: 'Conseils Quotidiens Santé & Bien-être',
    tipsSubtitle: 'Recommandations pour maintenir un système immunitaire optimal.',
    bookmark: 'Sauvegarder',
    bookmarked: 'Sauvegardé',

    chatbotTitle: 'Assistant HealthAI 24/7',
    chatbotSubtitle: 'Posez vos questions de santé pour recevoir des conseils vérifiés.',
    chatbotHeaderTitle: 'Assistant HealthAI',
    chatbotHeaderStatus: 'En Ligne',
    chatPlaceholder: 'Posez votre question (ex. Comment éviter la dengue ?)...',
    send: 'Envoyer',
    clearChat: 'Effacer le Chat',
    exportChat: 'Exporter',
    historyBtn: 'Historique',
    disclaimer: 'Avertissement: HealthAI fournit des conseils éducatifs. En cas d\'urgence, consultez un médecin.',
    samplePromptTitle: 'Questions Suggérées:',

    faqTag: 'Base de Connaissances',
    faqTitle: 'Foire Aux Questions',
    faqSubtitle: 'Réponses rapides sur notre plateforme et la confidentialité.',
    faqQ1: 'Ce chatbot remplace-t-il la consultation d\'un médecin ?',
    faqA1: 'Non. HealthAI est un outil éducatif. En cas de symptômes graves, consultez un professionnel.',
    faqQ2: 'Mes données de santé sont-elles protégées ?',
    faqA2: 'Oui, à 100%. Nous ne conservons aucune donnée personnelle identifiable.',
    faqQ3: 'Quelles maladies sont répertoriées ?',
    faqA3: 'Plus de 50 maladies dont la Dengue, le Paludisme, le COVID-19, le Diabète et la Tuberculose.',
    faqQ4: 'Est-ce disponible 24h/24 et 7j/7 ?',
    faqA4: 'Oui, le service est accessible en continu.',
    faqQ5: 'Puis-je l\'utiliser sur mobile ?',
    faqA5: 'Oui, compatible avec tous les smartphones et tablettes.',
    faqQ6: 'D\'où proviennent les informations ?',
    faqA6: 'Elles sont issues des recommandations officielles de l\'OMS et des CDC.',

    contactTag: 'Contact',
    contactTitle: 'Contactez l\'Équipe HealthAI',
    contactSubtitle: 'Des questions ou suggestions ? Écrivez à notre équipe technique.',
    nameField: 'Nom Complet',
    emailField: 'Adresse E-mail',
    messageField: 'Votre Message',
    sendMessage: 'Envoyer le Message',
    contactAddressLabel: 'Siège Social',
    contactPhoneLabel: 'Assistance 24/7',
    contactEmailUsLabel: 'E-mail Officiel',

    copyright: '© 2026 Plateforme Santé Publique HealthAI. Tous droits réservés.',
    authTitle: 'Bienvenue sur HealthAI',
    authSubtitle: 'Connectez-vous pour enregistrer votre historique de recherche.',
    loginTab: 'Se Connecter',
    registerTab: 'Créer un Compte',
    googleBtn: 'Continuer avec Google',
    emailLabel: 'Adresse E-mail',
    passwordLabel: 'Mot de Passe',
    nameLabel: 'Nom Complet',
    alreadyAccount: 'Déjà un compte ?',
    noAccount: 'Pas encore de compte ?',
    historyTitle: 'Historique de Recherche',
    historySubtitle: 'Consultez vos anciennes questions et réponses.',
    noHistory: 'Aucun historique trouvé.',
    clearHistoryBtn: 'Tout Effacer',
    reloadQuery: 'Recharger dans le Chat',
    riskLow: 'Risque Faible',
    riskModerate: 'Risque Modéré',
    riskUrgent: 'Attention Urgente',

    symptomModalTitle: 'Évaluateur de Symptômes et Triage',
    symptomModalSubtitle: 'Sélectionnez vos symptômes pour obtenir une évaluation du risque.',
    evaluateBtn: 'Évaluer le Risque',
    resetBtn: 'Réinitialiser'
  },

  zh: {
    startChat: '开始咨询',
    exploreDiseases: '疾病探索',
    navHome: '首页',
    navFeatures: '核心功能',
    navDiseases: '疾病库',
    navTips: '健康指南',
    navChatbot: 'AI 助手',
    navFAQ: '常见问题',
    navContact: '联系我们',
    signIn: '登录',
    signOut: '退出登录',
    myHistory: '我的咨询历史',
    guestUser: '游客用户',
    selectLanguage: '选择语言',
    symptomCheckBtn: '自测症状评估',

    heroTag: '24/7 全天候 AI 公共卫生平台',
    heroTitle: '人工智能驱动的公共卫生与疾病预防聊天机器人',
    heroSubtitle: '通过 AI 驱动的健康指导、疾病预防与权威医疗知识，随时随地守护社区健康。',
    activeUsers: '已守护的活跃用户',
    verifiedArticles: '已认证的临床文献',
    instantAnswers: '24/7 全天候 AI 健康支持',
    heroBadge: '赋能预防性医疗',

    howItWorksTag: '高效工作流程',
    howItWorksTitle: 'HealthAI 运作的 4 个步骤',
    howItWorksSubtitle: '从提交问题到获取权威医疗建议仅需数秒。',
    step1Title: '提出健康疑问',
    step1Desc: '用日常语言输入或语音描述您的症状与健康疑问。',
    step1Tag: '步骤 1：输入',
    step2Title: 'AI 智能分析',
    step2Desc: '医学专用语言模型评估关键词与症状严重程度。',
    step2Tag: '步骤 2：分析',
    step3Title: '检索权威知识库',
    step3Desc: '比对 WHO 和 CDC 权威公共卫生数据库。',
    step3Tag: '步骤 3：核实',
    step4Title: '生成指导方案',
    step4Desc: '提供清晰的预防措施与风险评估建议。',
    step4Tag: '步骤 4：输出',

    statsTag: '公共卫生成效',
    statsTitle: '值得信赖的全球健康数据',
    statsSubtitle: '用实时数据展示我们守护公众健康的承诺。',
    stat1Value: '100,000+',
    stat1Label: '受益人群',
    stat1Desc: '在 40 多个国家提供实时预防指导。',
    stat2Value: '50+',
    stat2Label: '收录疾病种类',
    stat2Desc: '全面覆盖传染病与慢性常见疾病。',
    stat3Value: '99.4%',
    stat3Label: '临床匹配准确率',
    stat3Desc: '严格符合世界卫生组织分诊标准。',
    stat4Value: '24/7',
    stat4Label: '即时响应',
    stat4Desc: '无需等待，零延迟问答。',

    whyTag: '为公众福祉打造',
    whyTitle: '为什么广大社区信任 HealthAI',
    whySubtitle: '将先进 AI 科技与流行病学标准深度结合。',
    why1Title: '基于循证医学',
    why1Desc: '所有解答均经过 WHO 和 CDC 指南核实。',
    why2Title: '隐私安全无忧',
    why2Desc: '实行零个人身份信息保留政策，完全匿名。',
    why3Title: '多语言无障碍',
    why3Desc: '支持全球 10 种主要语言即时翻译。',
    why4Title: '简单易用',
    why4Desc: '界面直观，适合各类人群便捷使用。',

    featuresTag: '全方位服务',
    featuresTitle: '专为现代公共卫生打造',
    featuresSubtitle: '探索 AI 驱动的核心功能，随时守护您的健康。',
    filterAll: '全部功能 (10)',
    filterAI: 'AI 核心',
    filterPrevention: '预防健康',
    filterSecurity: '安全隐私',
    searchFeaturesPlaceholder: '搜索功能...',
    verifiedCapability: '已验证功能',
    launchTool: '启动交互工具',

    diseasesTag: '公共卫生知识库',
    diseasesTitle: '疾病预防与健康科普中心',
    diseasesSubtitle: '查阅权威验证的症状、病因与预防指南。',
    searchDiseasesPlaceholder: '按疾病名称、症状或病因搜索...',
    allCategories: '全部分类',
    symptomsLabel: '核心症状：',
    preventionLabel: '预防策略：',
    learnDetails: '查看详情与预防方案',
    icdCodeLabel: 'ICD 编码',
    transmissionLabel: '传播途径',
    symptomsHeader: '临床表现与症状',
    causesHeader: '病因与发病机制',
    preventionHeader: '预防措施与指南',
    emergencyHeader: '紧急就医预警：',
    shareGuide: '分享指南',
    closeProfile: '关闭',

    tipsTag: '每日养生',
    tipsTitle: '每日健康与养生指南',
    tipsSubtitle: '提升免疫力与维持健康的科学建议。',
    bookmark: '收藏',
    bookmarked: '已收藏',

    chatbotTitle: '24×7 全天候 HealthAI 助手',
    chatbotSubtitle: '随时用自然语言提出健康疑问，获取权威预防指导。',
    chatbotHeaderTitle: 'HealthAI 智能助手',
    chatbotHeaderStatus: '在线',
    chatPlaceholder: '向 HealthAI 提问（例如：如何预防登革热？）...',
    send: '发送',
    clearChat: '清空聊天',
    exportChat: '导出记录',
    historyBtn: '咨询历史',
    disclaimer: '声明：HealthAI 提供健康普及信息。重症请立即就医。',
    samplePromptTitle: '推荐问题：',

    faqTag: '常见疑问',
    faqTitle: '常见问题解答',
    faqSubtitle: '快速了解我们的医疗 AI 平台与隐私政策。',
    faqQ1: '此机器人是否能替代医生诊断？',
    faqA1: '不能。HealthAI 是科普与预防工具。如出现严重症状请及时就医。',
    faqQ2: '我的咨询内容是否安全保密？',
    faqA2: '是的，100% 保密。我们采用最高级别的数据加密传输。',
    faqQ3: '包含哪些疾病的科普信息？',
    faqA3: '涵盖登革热、疟疾、新冠、糖尿病、肺结核、伤寒等 50 多种疾病。',
    faqQ4: '平台是否全天候可用？',
    faqA4: '是的，平台 7×24 小时无间断运行。',
    faqQ5: '是否支持手机和平板使用？',
    faqA5: '支持。适配 iOS、Android 和电脑浏览器。',
    faqQ6: '医学数据的来源是什么？',
    faqA6: '综合自世界卫生组织 (WHO) 及 CDC 的公开文献与指南。',

    contactTag: '联系我们',
    contactTitle: '联系 HealthAI 团队',
    contactSubtitle: '如有反馈或合作需求，欢迎随时联系我们。',
    nameField: '真实姓名',
    emailField: '电子邮箱',
    messageField: '留言内容',
    sendMessage: '发送留言',
    contactAddressLabel: '总部地址',
    contactPhoneLabel: '24/7 服务热线',
    contactEmailUsLabel: '官方邮箱',

    copyright: '© 2026 HealthAI 公共卫生平台。保留所有权利。',
    authTitle: '欢迎使用 HealthAI',
    authSubtitle: '登录账号以多端同步您的健康咨询历史。',
    loginTab: '登录',
    registerTab: '注册账号',
    googleBtn: '使用 Google 账号登录',
    emailLabel: '电子邮箱',
    passwordLabel: '密码',
    nameLabel: '真实姓名',
    alreadyAccount: '已有账号？',
    noAccount: '还没有账号？',
    historyTitle: '您的咨询历史记录',
    historySubtitle: '查看您过往的健康提问与 AI 解答。',
    noHistory: '暂无历史记录。',
    clearHistoryBtn: '清空所有历史',
    reloadQuery: '重新在对话框中打开',
    riskLow: '低风险',
    riskModerate: '中度风险',
    riskUrgent: '需紧急就医',

    symptomModalTitle: '自测症状评估与分诊',
    symptomModalSubtitle: '勾选您的症状以快速获取健康风险评估。',
    evaluateBtn: '评估风险等级',
    resetBtn: '重置勾选'
  },

  de: {
    startChat: 'Chat Starten',
    exploreDiseases: 'Krankheiten',
    navHome: 'Startseite',
    navFeatures: 'Funktionen',
    navDiseases: 'Krankheiten',
    navTips: 'Gesundheitstipps',
    navChatbot: 'KI-Chatbot',
    navFAQ: 'FAQ',
    navContact: 'Kontakt',
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    myHistory: 'Mein Verlauf',
    guestUser: 'Gast-Benutzer',
    selectLanguage: 'Sprache Wählen',
    symptomCheckBtn: 'Symptom-Check',

    heroTag: '24/7 KI-Plattform für öffentliche Gesundheit',
    heroTitle: 'KI-gestützter Chatbot für Gesundheitsaufklärung',
    heroSubtitle: 'Unterstützung von Gemeinschaften mit KI-gestützter Gesundheitsberatung und verlässlichen Präventionsinformationen.',
    activeUsers: 'Geschützte Aktive Nutzer',
    verifiedArticles: 'Verifizierte Medizinische Quellen',
    instantAnswers: '24/7 KI-Gesundheitssupport',
    heroBadge: 'Präventionspflege Fördern',

    howItWorksTag: 'Einfacher Ablauf',
    howItWorksTitle: 'Wie HealthAI in 4 Schritten Funktioniert',
    howItWorksSubtitle: 'Von Ihrer Frage zu verifizierten medizinischen Ratschlägen in Sekunden.',
    step1Title: 'Frage Stellen',
    step1Desc: 'Geben Sie Ihre Symptome oder Fragen in natürlicher Sprache ein.',
    step1Tag: 'Schritt 1: Eingabe',
    step2Title: 'KI-Analyse',
    step2Desc: 'Unser medizinisches KI-Modell analysiert Schlüsselwörter und Schweregrad.',
    step2Tag: 'Schritt 2: Analyse',
    step3Title: 'Verifizierte Daten',
    step3Desc: 'Abgleich mit Datenbanken der WHO und CDC.',
    step3Tag: 'Schritt 3: Überprüfung',
    step4Title: 'Praktische Ratschläge',
    step4Desc: 'Klar verständliche Empfehlungen zur Prävention.',
    step4Tag: 'Schritt 4: Ergebnis',

    statsTag: 'Messbare Wirkung',
    statsTitle: 'Globale Gesundheitsdaten im Überblick',
    statsSubtitle: 'Echtzeit-Metriken unseres Engagements.',
    stat1Value: '100.000+',
    stat1Label: 'Unterstützte Personen',
    stat1Desc: 'In über 40 Ländern weltweit.',
    stat2Value: '50+',
    stat2Label: 'Erfasste Krankheiten',
    stat2Desc: 'Umfassende Abdeckung infektiöser und chronischer Leiden.',
    stat3Value: '99.4%',
    stat3Label: 'Klinische Genauigkeit',
    stat3Desc: 'Überprüft nach WHO-Triage-Standards.',
    stat4Value: '24/7',
    stat4Label: 'Sofortige Antwort',
    stat4Desc: 'Ohne Wartezeit.',

    whyTag: 'Für das Gemeinwohl',
    whyTitle: 'Warum Menschen HealthAI Vertrauen',
    whySubtitle: 'Verbindung von KI-Technologie mit medizinischen Standards.',
    why1Title: 'Evidenzbasierter Ansatz',
    why1Desc: 'Geprüft nach Vorgaben von WHO und CDC.',
    why2Title: 'Höchster Datenschutz',
    why2Desc: 'Keine Speicherung persönlicher Daten. 100% anonym.',
    why3Title: 'Mehrsprachig',
    why3Desc: 'Sofortübersetzung in 10 globale Sprachen.',
    why4Title: 'Einfach & Zugänglich',
    why4Desc: 'Intuitive Benutzeroberfläche für jedermann.',

    featuresTag: 'Funktionsumfang',
    featuresTitle: 'Für die Moderne Gesundheit Entwickelt',
    featuresSubtitle: 'Entdecken Sie KI-Funktionen für Ihre Prävention.',
    filterAll: 'Alle Funktionen (10)',
    filterAI: 'Fokus KI',
    filterPrevention: 'Fokus Prävention',
    filterSecurity: 'Fokus Sicherheit',
    searchFeaturesPlaceholder: 'Funktion suchen...',
    verifiedCapability: 'Geprüfte Funktion',
    launchTool: 'Tool Starten',

    diseasesTag: 'Medizinische Datenbank',
    diseasesTitle: 'Zentrum für Krankheitsaufklärung',
    diseasesSubtitle: 'Symptome, Ursachen und Prävention auf einen Blick.',
    searchDiseasesPlaceholder: 'Nach Name, Symptom oder Ursache suchen...',
    allCategories: 'Alle Kategorien',
    symptomsLabel: 'Hauptsymptome:',
    preventionLabel: 'Präventionsstrategie:',
    learnDetails: 'Details & Prävention',
    icdCodeLabel: 'ICD-Code',
    transmissionLabel: 'Übertragungsweg',
    symptomsHeader: 'Klinische Symptome',
    causesHeader: 'Ursachen & Ätiologie',
    preventionHeader: 'Präventionsprotokoll',
    emergencyHeader: 'Notfall-Warnung:',
    shareGuide: 'Teilen',
    closeProfile: 'Schließen',

    tipsTag: 'Tägliche Gesundheit',
    tipsTitle: 'Tägliche Gesundheitstipps',
    tipsSubtitle: 'Empfehlungen für ein starkes Immunsystem.',
    bookmark: 'Merken',
    bookmarked: 'Gespeichert',

    chatbotTitle: '24×7 KI-Gesundheitsassistent',
    chatbotSubtitle: 'Stellen Sie Ihre Fragen in natürlicher Sprache.',
    chatbotHeaderTitle: 'HealthAI Assistent',
    chatbotHeaderStatus: 'Online',
    chatPlaceholder: 'Frage eingeben (z.B. Wie beuge ich Dengue vor?)...',
    send: 'Senden',
    clearChat: 'Löschen',
    exportChat: 'Exportieren',
    historyBtn: 'Verlauf',
    disclaimer: 'Hinweis: HealthAI bietet Bildungsinformationen. Im Notfall Arzt aufsuchen.',
    samplePromptTitle: 'Vorgeschlagene Fragen:',

    faqTag: 'Wissensdatenbank',
    faqTitle: 'Häufig Gestellte Fragen',
    faqSubtitle: 'Schnelle Antworten zu unserer Plattform und Datenschutz.',
    faqQ1: 'Ersetzt der Chatbot einen Arztbesuch?',
    faqA1: 'Nein. HealthAI ist ein Bildungstool. Bei schweren Symptomen bitte sofort einen Arzt aufsuchen.',
    faqQ2: 'Sind meine Daten sicher?',
    faqA2: 'Ja, zu 100%. Keine Speicherung persönlicher Identifikatoren.',
    faqQ3: 'Welche Krankheiten werden abgedeckt?',
    faqA3: 'Über 50 Krankheiten wie Dengue, Malaria, COVID-19, Diabetes und Tbc.',
    faqQ4: 'Ist HealthAI rund um die Uhr erreichbar?',
    faqA4: 'Ja, 24 Stunden am Tag, 7 Tage die Woche.',
    faqQ5: 'Kann ich es auf dem Smartphone nutzen?',
    faqA5: 'Ja, optimiert für alle mobilen Geräte und Browser.',
    faqQ6: 'Woher stammen die Informationen?',
    faqA6: 'Aus verifizierten Richtlinien von WHO und CDC.',

    contactTag: 'Kontakt',
    contactTitle: 'Kontaktieren Sie HealthAI',
    contactSubtitle: 'Haben Sie Fragen oder Feedback? Schreiben Sie uns.',
    nameField: 'Vollständiger Name',
    emailField: 'E-Mail-Adresse',
    messageField: 'Ihre Nachricht',
    sendMessage: 'Nachricht Senden',
    contactAddressLabel: 'Hauptsitz',
    contactPhoneLabel: '24/7 Hotline',
    contactEmailUsLabel: 'Offizielle E-Mail',

    copyright: '© 2026 HealthAI Plattform. Alle Rechte vorbehalten.',
    authTitle: 'Willkommen bei HealthAI',
    authSubtitle: 'Melden Sie sich an, um Ihren Verlauf zu speichern.',
    loginTab: 'Anmelden',
    registerTab: 'Konto Erstellen',
    googleBtn: 'Mit Google Fortfahren',
    emailLabel: 'E-Mail-Adresse',
    passwordLabel: 'Passwort',
    nameLabel: 'Vollständiger Name',
    alreadyAccount: 'Bereits ein Konto?',
    noAccount: 'Noch kein Konto?',
    historyTitle: 'Such- & Chat-Verlauf',
    historySubtitle: 'Überprüfen Sie bisherige Anfragen.',
    noHistory: 'Kein Verlauf gefunden.',
    clearHistoryBtn: 'Alles Löschen',
    reloadQuery: 'Im Chat Öffnen',
    riskLow: 'Geringes Risiko',
    riskModerate: 'Mittleres Risiko',
    riskUrgent: 'Dringende Hilfe',

    symptomModalTitle: 'Symptom-Bewertung & Triage',
    symptomModalSubtitle: 'Wählen Sie Ihre Symptome für eine Einschätzung.',
    evaluateBtn: 'Risiko Bewerten',
    resetBtn: 'Zurücksetzen'
  },

  te: {
    startChat: 'చాట్ ప్రారంభించండి',
    exploreDiseases: 'వ్యాధులను చూడండి',
    navHome: 'హోమ్',
    navFeatures: 'లక్షణాలు',
    navDiseases: 'వ్యాధులు',
    navTips: 'ఆరోగ్య మార్గదర్శకాలు',
    navChatbot: 'AI బాట్',
    navFAQ: 'తరచుగా అడిగే ప్రశ్నలు',
    navContact: 'సంప్రదించండి',
    signIn: 'సైన్ ఇన్',
    signOut: 'సైన్ అవుట్',
    myHistory: 'చాట్ హిస్టరీ',
    guestUser: 'అతిథి వినియోగదారు',
    selectLanguage: 'భాషను ఎంచుకోండి',
    symptomCheckBtn: 'లక్షణాల తనిఖీ',

    newChat: 'కొత్త చాట్',
    textToSpeech: 'వాయిస్ చదవడం',
    navImages: 'చిత్రాలు',
    recents: 'ఇటీవలి చాట్లు',
    viewAll: 'అన్నీ చూడండి',
    connectedAs: 'లాగిన్ ఖాతా:',
    verifiedRepo: 'WHO & CDC ధృవీకరించిన సమాచారం',
    whereToBegin: 'మనం ఎక్కడి నుండి ప్రారంభిద్దాం?',
    heroCanvasSubtitle: 'లక్షణాలు, వ్యాధి నివారణ, టీకాల మార్గదర్శకాలు లేదా ప్రజా ఆరోగ్య రక్షణ గురించి హెల్త్-AI ని అడగండి.',
    askAnything: 'ఏదైనా అడగండి...',
    createAnImage: 'చిత్రాన్ని సృష్టించండి',
    visualDiseaseGuide: 'దృశ్య వ్యాధి మార్గదర్శకం',
    writeOrEdit: 'రాయండి లేదా సవరించండి',
    healthGuidelines: 'ఆరోగ్య మార్గదర్శకాలు',
    searchTheWeb: 'వెబ్‌లో వెతకండి',
    publicHealthRepo: 'ప్రజా ఆరోగ్య డేటాబేస్',
    welcomeMessage: 'నమస్తే! నేను హెల్త్-AI, మీ 24/7 ప్రజా ఆరోగ్య సహాయకుడిని. వ్యాధి లక్షణాలు, నివారణ మార్గాలు, టీకాల వివరాలు లేదా ఆరోగ్య చిట్కాల గురించి నన్ను అడగండి.',

    heroTag: '24/7 AI ప్రజా ఆరోగ్య వేదిక',
    heroTitle: 'వ్యాధి అవగాహన కోసం AI ఆధారిత ప్రజా ఆరోగ్య చాట్‌బాట్',
    heroSubtitle: 'AI ఆరోగ్య మార్గదర్శకత్వం, వ్యాధి అవగాహన మరియు నివారణ సంరక్షణతో సమాజాలను సాధికారపరచడం.',
    activeUsers: 'రక్షించబడిన క్రియాశీల వినియోగదారులు',
    verifiedArticles: 'ధృవీకరించబడిన వైద్య ఆధారాలు',
    instantAnswers: '24/7 AI ఆరోగ్య సహాయం',
    heroBadge: 'నివారణ సంరక్షణ ప్రాధాన్యత',

    howItWorksTag: 'సులభమైన విధానం',
    howItWorksTitle: 'హెల్త్-AI పనిచేసే 4 సులభమైన దశలు',
    howItWorksSubtitle: 'మీ ప్రశ్న నుండి వైద్య సలహా వరకు సెకన్లలో సమాచారం పొందండి.',
    step1Title: 'ప్రశ్న అడగండి',
    step1Desc: 'మీ ఆరోగ్య సందేహాలను మీ స్వంత భాషలో టైప్ చేయండి.',
    step1Tag: 'దశ 1: ఇన్‌పుట్',
    step2Title: 'AI విశ్లేషణ',
    step2Desc: 'మా వైద్య AI మోడల్ మీ లక్షణాలను విశ్లేషిస్తుంది.',
    step2Tag: 'దశ 2: ప్రాసెసింగ్',
    step3Title: 'సమాచారం సేకరణ',
    step3Desc: 'WHO మరియు CDC ప్రపంచ ఆరోగ్య డేటాబేస్ ద్వారా తనిఖీ చేస్తుంది.',
    step3Tag: 'దశ 3: ధృవీకరణ',
    step4Title: 'సరైన మార్గదర్శకత్వం',
    step4Desc: 'స్పష్టమైన నివారణ మార్గాలు మరియు సూచనలను అందిస్తుంది.',
    step4Tag: 'దశ 4: ఫలితం',

    statsTag: 'ప్రజా సేవ',
    statsTitle: 'ప్రపంచ ఆరోగ్య సమాచారం',
    statsSubtitle: 'ప్రజా ఆరోగ్యంపై మా బాధ్యతకు నిజమైన నిదర్శనం.',
    stat1Value: '100,000+',
    stat1Label: 'సహాయం పొందిన ప్రజలు',
    stat1Desc: '40 కి పైగా దేశాలలో తక్షణ సహాయం.',
    stat2Value: '50+',
    stat2Label: 'వ్యాధుల సమాచారం',
    stat2Desc: 'ప్రధాన అంటువ్యాధులు మరియు దీర్ఘకాలిక వ్యాధుల వివరాలు.',
    stat3Value: '99.4%',
    stat3Label: 'వైద్య ఖచ్చితత్వం',
    stat3Desc: 'ప్రపంచ ఆరోగ్య సంస్థ ప్రమాణాలకు అనుగుణంగా.',
    stat4Value: '24/7',
    stat4Label: 'తక్షణ సేవ',
    stat4Desc: 'ఎలాంటి నిరీక్షణ లేకుండా ఉచిత సహాయం.',

    whyTag: 'ప్రజా సంక్షేమం కోసం',
    whyTitle: 'ప్రజలు హెల్త్-AI ని ఎందుకు నమ్ముతారు',
    whySubtitle: 'అధునాతన AI సాంకేతికత మరియు వైద్య ప్రమాణాల సమ్మేళనం.',
    why1Title: 'ధృవీకరించబడిన సమాచారం',
    why1Desc: 'అన్ని సమాధానాలు WHO మరియు CDC ద్వారా ధృవీకరించబడ్డాయి.',
    why2Title: 'పూర్తి భద్రత',
    why2Desc: 'మీ వ్యక్తిగత వివరాలు ఎప్పటికీ గోప్యంగా ఉంటాయి.',
    why3Title: 'బహుభాషా సదుపాయం',
    why3Desc: '10 ప్రధాన ప్రపంచ భాషలలో తక్షణ సమాచారం.',
    why4Title: 'అందరికీ సులభం',
    why4Desc: 'ఎవరైనా సులభంగా ఉపయోగించగల సరళమైన రూపకల్పన.',

    featuresTag: 'సమగ్ర సేవలు',
    featuresTitle: 'ఆధునిక ప్రజా ఆరోగ్యం కోసం రూపకల్పన',
    featuresSubtitle: 'మీ ఆరోగ్య రక్షణ కోసం AI ఆధారిత సౌకర్యాలు.',
    filterAll: 'అన్ని సేవలు (10)',
    filterAI: 'AI ఫోకస్',
    filterPrevention: 'నివారణ ఫోకస్',
    filterSecurity: 'భద్రత ఫోకస్',
    searchFeaturesPlaceholder: 'సేవలను వెతకండి...',
    verifiedCapability: 'ధృవీకరించబడిన సౌకర్యం',
    launchTool: 'సాధనాన్ని ప్రారంభించు',

    diseasesTag: 'వైద్య సమాచారం',
    diseasesTitle: 'వ్యాధి అవగాహన మరియు నివారణ కేంద్రం',
    diseasesSubtitle: 'లక్షణాలు, కారణాలు మరియు నివారణ మార్గాల వివరాలు.',
    searchDiseasesPlaceholder: 'వ్యాధి లేదా లక్షణాల ద్వారా వెతకండి...',
    allCategories: 'అన్ని విభాగాలు',
    symptomsLabel: 'ముఖ్య లక్షణాలు:',
    preventionLabel: 'నివారణ మార్గాలు:',
    learnDetails: 'వివరాలు చూడండి',
    icdCodeLabel: 'ICD కోడ్',
    transmissionLabel: 'వ్యాపించే విధానం',
    symptomsHeader: 'వైద్య లక్షణాలు',
    causesHeader: 'కారణాలు',
    preventionHeader: 'నివారణ నిబంధనలు',
    emergencyHeader: 'అత్యవసర హెచ్చరిక:',
    shareGuide: 'షేర్ చేయి',
    closeProfile: 'మూసివేయి',

    tipsTag: 'రోజువారీ ఆరోగ్యం',
    tipsTitle: 'రోజువారీ ఆరోగ్య సూచనలు',
    tipsSubtitle: 'రోగనిరోధక శక్తిని పెంచుకోవడానికి ఆరోగ్య మార్గాలు.',
    bookmark: 'సేవ్ చేయి',
    bookmarked: 'సేవ్ చేయబడింది',

    chatbotTitle: '24×7 హెల్త్-AI సహాయకుడు',
    chatbotSubtitle: 'మీ ఆరోగ్య సందేహాలను అడిగి సరైన సమాచారం పొందండి.',
    chatbotHeaderTitle: 'హెల్త్-AI అసిస్టెంట్',
    chatbotHeaderStatus: 'ఆన్‌లైన్',
    chatPlaceholder: 'ఆరోగ్య సందేహాన్ని టైప్ చేయండి (ఉదా: డెంగ్యూ నివారణ ఎలా?)...',
    send: 'పంపు',
    clearChat: 'చాట్ తొలగించు',
    exportChat: 'డౌన్‌లోడ్',
    historyBtn: 'హిస్టరీ',
    disclaimer: 'గమనిక: హెల్త్-AI అవగాహన కోసం సమాచారాన్ని అందిస్తుంది. అత్యవసర పరిస్థితిలో వైద్యుడిని సంప్రదించండి.',
    samplePromptTitle: 'సూచించిన ప్రశ్నలు:',

    faqTag: 'సందేహాలు',
    faqTitle: 'తరచుగా అడిగే ప్రశ్నలు',
    faqSubtitle: 'మా వైద్య AI మరియు భద్రత గురించిన సమాధానాలు.',
    faqQ1: 'ఈ చాట్‌బాట్ డాక్టర్ సలహాకు ప్రత్యామ్నాయమా?',
    faqA1: 'కాదు. హెల్త్-AI కేవలం అవగాహన కోసం తయారుచేయబడింది. తీవ్రమైన పరిస్థితిలో డాక్టర్‌ను కలవండి.',
    faqQ2: 'నా ఆరోగ్య సమాచారం భద్రంగా ఉంటుందా?',
    faqA2: 'అవును, 100% భద్రం. మీ వ్యక్తిగత వివరాలను మేము సేకరించము.',
    faqQ3: 'ఏ ఏ వ్యాధుల సమాచారం ఉంది?',
    faqA3: 'డెంగ్యూ, మలేరియా, కోవిడ్, డయాబెటిస్, క్షయ మొదలైన 50 కి పైగా వ్యాధుల సమాచారం ఉంది.',
    faqQ4: 'ఈ సేవ 24 గంటలూ అందుబాటులో ఉంటుందా?',
    faqA4: 'అవును, 24/7 ఎప్పుడైనా ఉపయోగించుకోవచ్చు.',
    faqQ5: 'మొబైల్‌లో ఉపయోగించవచ్చా?',
    faqA5: 'అవును, ఫోన్, టాబ్లెట్ మరియు కంప్యూటర్లలో పని చేస్తుంది.',
    faqQ6: 'ఈ సమాచారం ఎక్కడి నుండి తీసుకున్నారు?',
    faqA6: 'ప్రపంచ ఆరోగ్య సంస్థ (WHO) మరియు CDC నివేదికల నుండి.',

    contactTag: 'సంప్రదించండి',
    contactTitle: 'హెల్త్-AI ని సంప్రదించండి',
    contactSubtitle: 'మీ అభిప్రాయాలు లేదా సందేహాలు ఉంటే మాకు పంపండి.',
    nameField: 'పూర్తి పేరు',
    emailField: 'ఈమెయిల్ చిరునామా',
    messageField: 'మీ సందేశం',
    sendMessage: 'సందేశం పంపు',
    contactAddressLabel: 'ప్రధాన కార్యాలయం',
    contactPhoneLabel: '24/7 హెల్ప్‌లైన్',
    contactEmailUsLabel: 'అధికారిక ఈమెయిల్',

    copyright: '© 2026 హెల్త్-AI ప్రజా ఆరోగ్య వేదిక. సర్వ హక్కులూ ప్రత్యేకించబడినవి.',
    authTitle: 'హెల్త్-AI కి స్వాగతం',
    authSubtitle: 'మీ చాట్ హిస్టరీని భద్రపరుచుకోవడానికి సైన్ ఇన్ చేయండి.',
    loginTab: 'సైన్ ఇన్',
    registerTab: 'ఖాతా తెరువు',
    googleBtn: 'Google తో కొనసాగించండి',
    emailLabel: 'ఈమెయిల్',
    passwordLabel: 'పాస్‌వర్డ్',
    nameLabel: 'పూర్తి పేరు',
    alreadyAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    noAccount: 'ఖాతా లేదా?',
    historyTitle: 'మీ సెర్చ్ మరియు చాట్ హిస్టరీ',
    historySubtitle: 'మీరు గతంలో అడిగిన ప్రశ్నలు చూడండి.',
    noHistory: 'గత చరిత్ర ఏమీ లేదు.',
    clearHistoryBtn: 'మొత్తం తొలగించు',
    reloadQuery: 'చాట్‌లో తెరువు',
    riskLow: 'తక్కువ ప్రమాదం',
    riskModerate: 'మధ్యస్థ ప్రమాదం',
    riskUrgent: 'వెంటనే వైద్యుడిని సంప్రదించండి',

    symptomModalTitle: 'లక్షణాల పరీక్ష మరియు ప్రమాద అంచనా',
    symptomModalSubtitle: 'మీ లక్షణాలను ఎంచుకుని తక్షణ అంచనా పొందండి.',
    evaluateBtn: 'ప్రమాద స్థాయి తనిఖీ',
    resetBtn: 'రీసెట్ చేయి'
  },

  ar: {
    startChat: 'بدء المحادثة',
    exploreDiseases: 'استكشاف الأمراض',
    navHome: 'الرئيسية',
    navFeatures: 'المميزات',
    navDiseases: 'الأمراض',
    navTips: 'نصائح صحية',
    navChatbot: 'المساعد الذكي',
    navFAQ: 'الأسئلة الشائعة',
    navContact: 'اتصل بنا',
    signIn: 'تسجيل الدخول',
    signOut: 'تسجيل الخروج',
    myHistory: 'سجل المحادثات',
    guestUser: 'مستخدم زائر',
    selectLanguage: 'اختر اللغة',
    symptomCheckBtn: 'فحص الأعراض',

    heroTag: 'منصة الصحة العامة بالذكاء الاصطناعي 24/7',
    heroTitle: 'مساعد الذكاء الاصطناعي للصحة العامة والتوعية بالأمراض',
    heroSubtitle: 'تمكين المجتمعات من خلال الإرشادات الصحية القائمة على الذكاء الاصطناعي والتوعية بالأمراض والرعاية الوقائية.',
    activeUsers: 'مستخدم نشط محمي',
    verifiedArticles: 'مصدر طبي موثق',
    instantAnswers: 'دعم صحي 24/7',
    heroBadge: 'تعزيز الرعاية الوقائية',

    howItWorksTag: 'سير عمل سلس',
    howItWorksTitle: 'كيف يعمل HealthAI في 4 خطوات',
    howItWorksSubtitle: 'من سؤالك إلى نصيحة طبية موثوقة في ثوانٍ معدودة.',
    step1Title: 'اطرح سؤالاً صحياً',
    step1Desc: 'اكتب أعراضك أو استفسارك بلغة طبيعية.',
    step1Tag: 'الخطوة 1: المدخلات',
    step2Title: 'تحليل الذكاء الاصطناعي',
    step2Desc: 'يقيم نموذجنا الطبي الكلمات المفتاحية وشدة الأعراض.',
    step2Tag: 'الخطوة 2: المعالجة',
    step3Title: 'استرجاع معلومات موثوقة',
    step3Desc: 'يقارن البيانات مع قواعد منظمة الصحة العالمية و CDC.',
    step3Tag: 'الخطوة 3: التحقق',
    step4Title: 'إرشادات عملية',
    step4Desc: 'يقدم خطوات وقائية واضحة ومستويات الخطورة.',
    step4Tag: 'الخطوة 4: النتيجة',

    statsTag: 'تأثير عام ملموس',
    statsTitle: 'بيانات صحية عالمية موثوقة',
    statsSubtitle: 'مقاييس فورية تعكس التزامنا بالتوعية الصحية.',
    stat1Value: '100,000+',
    stat1Label: 'شخص تم مساعدتهم',
    stat1Desc: 'إرشادات وقائية فورية في أكثر من 40 دولة.',
    stat2Value: '50+',
    stat2Label: 'مرض مفهرس',
    stat2Desc: 'تغطية شاملة للأمراض المعدية والمزمنة.',
    stat3Value: '99.4%',
    stat3Label: 'دقة طبية',
    stat3Desc: 'مطابق لمعايير الفرز الطبي لمنظمة الصحة العالمية.',
    stat4Value: '24/7',
    stat4Label: 'دعم فوري',
    stat4Desc: 'استجابة سريعة بدون انتظار.'
  },

  ja: {
    heroBadge: '予防医療の推進',

    howItWorksTag: 'スムーズな流れ',
    howItWorksTitle: 'HealthAIの4つのステップ',
    howItWorksSubtitle: '質問から信頼できる医療情報まで数秒で到達します。',
    step1Title: '質問を入力',
    step1Desc: '症状や疾病に関する質問を自然な言葉で入力します。',
    step1Tag: 'ステップ 1: 入力',
    step2Title: 'AIによる解析',
    step2Desc: '専用医療AIモデルがキーワードと緊急度を分析します。',
    step2Tag: 'ステップ 2: 解析',
    step3Title: '医学データベース検索',
    step3Desc: 'WHOやCDCの最新公衆衛生データと照合します。',
    step3Tag: 'ステップ 3: 検証',
    step4Title: 'アドバイス出力',
    step4Desc: '明確な予防手順とリスク評価を提供します。',
    step4Tag: 'ステップ 4: 結果',

    statsTag: '社会的影響',
    statsTitle: '信頼できる世界スケールの健康データ',
    statsSubtitle: '公衆衛生向上への取り組みを示すリアルタイム指標。',
    stat1Value: '100,000+',
    stat1Label: '支援された利用者',
    stat1Desc: '40カ国以上で即時の予防指導を提供。',
    stat2Value: '50+',
    stat2Label: '収録疾患数',
    stat2Desc: '感染症および慢性疾患をカバー。',
    stat3Value: '99.4%',
    stat3Label: '臨床一致率',
    stat3Desc: 'WHOトリアージ基準に基づき検証。',
    stat4Value: '24/7',
    stat4Label: '即時サポート',
    stat4Desc: '待ち時間なしで回答。',

    whyTag: '公共のために',
    whyTitle: 'HealthAIが選ばれる理由',
    whySubtitle: '最先端AI技術と疫学基準の融合。',
    why1Title: 'エビデンスに基づくエンジン',
    why1Desc: '回答はWHOおよびCDCガイドラインに準拠。',
    why2Title: '徹底したプライバシー保護',
    why2Desc: '個人情報は保持せず、完全匿名で利用可能。',
    why3Title: '多言語対応',
    why3Desc: '世界の主要10言語に即座に対応。',
    why4Title: '誰にでも使いやすい',
    why4Desc: '直感的なデザインで誰でも簡単に操作。',

    featuresTag: '充実した機能',
    featuresTitle: '現代の公衆衛生のために設計',
    featuresSubtitle: '健康を守るためのAI機能を体験してください。',
    filterAll: 'すべての機能 (10)',
    filterAI: 'AI機能',
    filterPrevention: '予防ケア',
    filterSecurity: 'セキュリティ',
    searchFeaturesPlaceholder: '機能を検索...',
    verifiedCapability: '検証済み機能',
    launchTool: 'ツールを起動',

    diseasesTag: '医療データベース',
    diseasesTitle: '疾患予防・啓発センター',
    diseasesSubtitle: '症状、原因、予防策の検証済み情報を閲覧。',
    searchDiseasesPlaceholder: '病名、症状、原因で検索...',
    allCategories: 'すべてのカテゴリー',
    symptomsLabel: '主な症状:',
    preventionLabel: '予防対策:',
    learnDetails: '詳細・予防策を見る',
    icdCodeLabel: 'ICDコード',
    transmissionLabel: '感染経路',
    symptomsHeader: '臨床症状',
    causesHeader: '原因・病因',
    preventionHeader: '予防プロトコル',
    emergencyHeader: '緊急受診警告:',
    shareGuide: '共有',
    closeProfile: '閉じる',

    tipsTag: '毎日のウェルネス',
    tipsTitle: '毎日の健康・ウェルネスガイド',
    tipsSubtitle: '免疫力を維持するための科学的アドバイス。',
    bookmark: '保存',
    bookmarked: '保存済み',

    chatbotTitle: '24×7 HealthAI アシスタント',
    chatbotSubtitle: '自然言語で質問し、信頼できる医療アドバイスを受信。',
    chatbotHeaderTitle: 'HealthAI アシスタント',
    chatbotHeaderStatus: 'オンライン',
    chatPlaceholder: '質問を入力（例：デング熱の予防方法は？）...',
    send: '送信',
    clearChat: '消去',
    exportChat: '出力',
    historyBtn: '履歴',
    disclaimer: '免責事項: HealthAIは教育情報を提供します。重症時は直ちに医師へ。',
    samplePromptTitle: 'おすすめの質問:',

    faqTag: 'よくある質問',
    faqTitle: 'よくある質問と回答',
    faqSubtitle: 'プラットフォームとプライバシーに関する質問。',
    faqQ1: '医師の診察の代わりになりますか？',
    faqA1: 'いいえ。HealthAIは教育ツールです。重い症状がある場合は直ちに医療機関へ。',
    faqQ2: 'プライバシーは守られますか？',
    faqA2: 'はい、100%保護されます。個人情報は保存されません。',
    faqQ3: 'どのような病気が対象ですか？',
    faqA3: 'デング熱、マラリア、COVID-19、糖尿病など50以上の疾患に対応しています。',
    faqQ4: '24時間利用できますか？',
    faqA4: 'はい、年中無休でいつでもご利用いただけます。',
    faqQ5: 'スマホで利用できますか？',
    faqA5: 'はい。スマートフォンやタブレットに最適化されています。',
    faqQ6: '情報の出典はどこですか？',
    faqA6: 'WHOおよびCDCの公式ガイドラインから作成されています。',

    contactTag: 'お問い合わせ',
    contactTitle: 'HealthAIチームにお問い合わせ',
    contactSubtitle: 'ご質問やご意見がございましたらご連絡ください。',
    nameField: 'お名前',
    emailField: 'メールアドレス',
    messageField: 'メッセージ',
    sendMessage: '送信する',
    contactAddressLabel: '本部所在地',
    contactPhoneLabel: '24時間ヘルプライン',
    contactEmailUsLabel: '公式メール',

    copyright: '© 2026 HealthAI 公衆衛生プラットフォーム. All rights reserved.',
    authTitle: 'HealthAIへようこそ',
    authSubtitle: 'ログインすると相談履歴を保存できます。',
    loginTab: 'ログイン',
    registerTab: '新規登録',
    googleBtn: 'Googleで継続',
    emailLabel: 'メールアドレス',
    passwordLabel: 'パスワード',
    nameLabel: 'お名前',
    alreadyAccount: 'アカウントをお持ちの方',
    noAccount: 'アカウントをお持ちでない方',
    historyTitle: '検索・相談履歴',
    historySubtitle: '過去の質問と回答を確認できます。',
    noHistory: '過去の履歴はありません。',
    clearHistoryBtn: 'すべて削除',
    reloadQuery: 'チャットで再表示',
    riskLow: '低リスク',
    riskModerate: '中度リスク',
    riskUrgent: '緊急受診推奨',

    symptomModalTitle: '症状セルフチェック＆リスク評価',
    symptomModalSubtitle: '当てはまる症状を選択してリスク評価を行います。',
    evaluateBtn: 'リスク評価を実行',
    resetBtn: 'リセット'
  },

  pt: {
    startChat: 'Iniciar Chat',
    exploreDiseases: 'Explorar Doenças',
    navHome: 'Início',
    navFeatures: 'Recursos',
    navDiseases: 'Doenças',
    navTips: 'Dicas de Saúde',
    navChatbot: 'Chatbot IA',
    navFAQ: 'Perguntas',
    navContact: 'Contato',
    signIn: 'Entrar',
    signOut: 'Sair',
    myHistory: 'Meu Histórico',
    guestUser: 'Usuário Convidado',
    selectLanguage: 'Selecionar Idioma',
    symptomCheckBtn: 'Checar Sintomas',

    heroTag: 'Plataforma de Saúde Pública com IA 24/7',
    heroTitle: 'Chatbot de Saúde Pública com IA para Conscientização',
    heroSubtitle: 'Empoderando comunidades com orientação médica por IA, prevenção de doenças e informações confiáveis a qualquer hora.',
    activeUsers: 'Usuários Ativos Protegidos',
    verifiedArticles: 'Fontes Médicas Verificadas',
    instantAnswers: 'Suporte de Saúde IA 24/7',
    heroBadge: 'Incentivando Cuidados Preventivos',

    howItWorksTag: 'Fluxo Simples',
    howItWorksTitle: 'Como o HealthAI Funciona em 4 Passos',
    howItWorksSubtitle: 'Da sua pergunta a orientações médicas confiáveis em segundos.',
    step1Title: 'Faça uma Pergunta',
    step1Desc: 'Digite seus sintomas ou dúvidas de saúde em linguagem natural.',
    step1Tag: 'Passo 1: Entrada',
    step2Title: 'Análise por IA',
    step2Desc: 'Nosso modelo médico avalia palavras-chave e gravidade.',
    step2Tag: 'Passo 2: Processamento',
    step3Title: 'Informação Verificada',
    step3Desc: 'Cruza dados com fontes oficiais da OMS e do CDC.',
    step3Tag: 'Passo 3: Verificação',
    step4Title: 'Orientação Prática',
    step4Desc: 'Fornece recomendações claras de prevenção.',
    step4Tag: 'Passo 4: Resultado',

    statsTag: 'Impacto Comprovado',
    statsTitle: 'Dados Globais de Saúde em Grande Escala',
    statsSubtitle: 'Métricas em tempo real do nosso compromisso com a saúde pública.',
    stat1Value: '100.000+',
    stat1Label: 'Pessoas Atendidas',
    stat1Desc: 'Com orientação preventiva imediata em mais de 40 países.',
    stat2Value: '50+',
    stat2Label: 'Doenças Catalogadas',
    stat2Desc: 'Cobertura de condições infecciosas e crônicas.',
    stat3Value: '99.4%',
    stat3Label: 'Precisão Clínica',
    stat3Desc: 'Validado com padrões de triagem da OMS.',
    stat4Value: '24/7',
    stat4Label: 'Suporte Imediato',
    stat4Desc: 'Sem tempo de espera.',

    whyTag: 'Para o Bem Público',
    whyTitle: 'Por que as Comunidades Confiam no HealthAI',
    whySubtitle: 'Unindo inteligência artificial com padrões médicos rigorosos.',
    why1Title: 'Base em Evidências',
    why1Desc: 'Todas as respostas são verificadas com a OMS e o CDC.',
    why2Title: 'Privacidade Garantida',
    why2Desc: 'Não armazenamos dados pessoais identificáveis. 100% anônimo.',
    why3Title: 'Multilíngue',
    why3Desc: 'Tradução instantânea em 10 idiomas globais.',
    why4Title: 'Acessível a Todos',
    why4Desc: 'Interface simples desenvolvida para qualquer usuário.',

    featuresTag: 'Recursos Completos',
    featuresTitle: 'Desenvolvido para a Saúde Pública Moderna',
    featuresSubtitle: 'Descubra recursos de IA projetados para orientar e proteger.',
    filterAll: 'Todos os Recursos (10)',
    filterAI: 'Foco em IA',
    filterPrevention: 'Foco em Prevenção',
    filterSecurity: 'Foco em Segurança',
    searchFeaturesPlaceholder: 'Buscar recurso...',
    verifiedCapability: 'Recurso Verificado',
    launchTool: 'Iniciar Ferramenta',

    diseasesTag: 'Base Médica',
    diseasesTitle: 'Centro de Prevenção de Doenças',
    diseasesSubtitle: 'Consulte sintomas, causas e prevenção verificados.',
    searchDiseasesPlaceholder: 'Buscar por nome, sintoma ou causa...',
    allCategories: 'Todas as Categorias',
    symptomsLabel: 'Principais Sintomas:',
    preventionLabel: 'Estratégia de Prevenção:',
    learnDetails: 'Ver Detalhes e Prevenção',
    icdCodeLabel: 'Código CID',
    transmissionLabel: 'Modo de Transmissão',
    symptomsHeader: 'Sintomas Clínicos',
    causesHeader: 'Causas e Etiologia',
    preventionHeader: 'Protocolo Preventivo',
    emergencyHeader: 'Alerta de Emergência:',
    shareGuide: 'Compartilhar',
    closeProfile: 'Fechar',

    tipsTag: 'Bem-Estar Diário',
    tipsTitle: 'Dicas Diárias de Saúde e Bem-Estar',
    tipsSubtitle: 'Recomendações para manter uma imunidade forte.',
    bookmark: 'Salvar',
    bookmarked: 'Salvo',

    chatbotTitle: 'Assistente HealthAI 24/7',
    chatbotSubtitle: 'Faça perguntas de saúde para receber orientação imediata.',
    chatbotHeaderTitle: 'Assistente HealthAI',
    chatbotHeaderStatus: 'Online',
    chatPlaceholder: 'Digite sua dúvida (ex: Como prevenir a dengue?)...',
    send: 'Enviar',
    clearChat: 'Limpar',
    exportChat: 'Exportar',
    historyBtn: 'Histórico',
    disclaimer: 'Aviso: O HealthAI fornece informações educacionais. Procure um médico em emergências.',
    samplePromptTitle: 'Perguntas Sugeridas:',

    faqTag: 'Perguntas Frequentes',
    faqTitle: 'Perguntas Frequentes',
    faqSubtitle: 'Respostas rápidas sobre nossa plataforma e privacidade.',
    faqQ1: 'O chatbot substitui a consulta com um médico?',
    faqA1: 'Não. O HealthAI é uma ferramenta educacional. Em emergências, consulte um médico.',
    faqQ2: 'Minhas informações de saúde estão seguras?',
    faqA2: 'Sim, 100%. Não armazenamos dados pessoais identificáveis.',
    faqQ3: 'Quais doenças estão catalogadas?',
    faqA3: 'Mais de 50 doenças como Dengue, Malária, COVID-19 e Diabetes.',
    faqQ4: 'O serviço está disponível 24 horas?',
    faqA4: 'Sim, funciona 24 horas por dia, 7 dias por semana.',
    faqQ5: 'Posso usar no celular?',
    faqA5: 'Sim, totalmente otimizado para celulares e tablets.',
    faqQ6: 'Qual a fonte das informações médicas?',
    faqA6: 'Baseado em diretrizes oficiais da OMS e do CDC.',

    contactTag: 'Contato',
    contactTitle: 'Fale com a Equipe HealthAI',
    contactSubtitle: 'Tem dúvidas ou sugestões? Escreva para nossa equipe.',
    nameField: 'Nome Completo',
    emailField: 'E-mail',
    messageField: 'Sua Mensagem',
    sendMessage: 'Enviar Mensagem',
    contactAddressLabel: 'Sede Principal',
    contactPhoneLabel: 'Linha 24/7',
    contactEmailUsLabel: 'E-mail Oficial',

    copyright: '© 2026 Plataforma de Saúde Pública HealthAI. Todos os direitos reservados.',
    authTitle: 'Bem-vindo ao HealthAI',
    authSubtitle: 'Faça login para salvar seu histórico de dúvidas.',
    loginTab: 'Entrar',
    registerTab: 'Criar Conta',
    googleBtn: 'Continuar com o Google',
    emailLabel: 'E-mail',
    passwordLabel: 'Senha',
    nameLabel: 'Nome Completo',
    alreadyAccount: 'Já tem uma conta?',
    noAccount: 'Não tem uma conta?',
    historyTitle: 'Histórico de Busca e Chat',
    historySubtitle: 'Revise suas dúvidas anteriores e respostas.',
    noHistory: 'Nenhum histórico encontrado.',
    clearHistoryBtn: 'Limpar Tudo',
    reloadQuery: 'Reabrir no Chat',
    riskLow: 'Risco Baixo',
    riskModerate: 'Risco Moderado',
    riskUrgent: 'Atenção Urgente',

    symptomModalTitle: 'Avaliador de Sintomas e Triagem',
    symptomModalSubtitle: 'Selecione seus sintomas para uma análise de risco.',
    evaluateBtn: 'Avaliar Risco',
    resetBtn: 'Reiniciar'
  }
};

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [theme, setTheme] = useState<Theme>(() => {
    const saved = localStorage.getItem('healthai-theme');
    if (saved === 'light' || saved === 'dark') return saved;
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  });

  const [language, setLanguage] = useState<Language>(() => {
    const savedLang = localStorage.getItem('healthai-lang') as Language;
    if (savedLang && translations[savedLang]) return savedLang;
    return 'en';
  });

  useEffect(() => {
    const root = document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
    localStorage.setItem('healthai-theme', theme);
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('healthai-lang', language);
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  const [isTtsEnabled, setIsTtsEnabled] = useState<boolean>(() => {
    return localStorage.getItem('healthai-tts') === 'true';
  });

  const toggleTts = () => {
    setIsTtsEnabled(prev => {
      const next = !prev;
      localStorage.setItem('healthai-tts', String(next));
      if (!next && 'speechSynthesis' in window) {
        window.speechSynthesis.cancel();
      }
      return next;
    });
  };

  const languageVoiceMap: Record<Language, string> = {
    en: 'en-US',
    es: 'es-ES',
    hi: 'hi-IN',
    fr: 'fr-FR',
    zh: 'zh-CN',
    de: 'de-DE',
    te: 'te-IN',
    ar: 'ar-SA',
    ja: 'ja-JP',
    pt: 'pt-BR'
  };

  const speakText = (text: string) => {
    if (!isTtsEnabled || !('speechSynthesis' in window)) return;
    window.speechSynthesis.cancel();
    const cleanText = text.replace(/[*#_`]/g, '').slice(0, 400);
    const utterance = new SpeechSynthesisUtterance(cleanText);
    const targetLangCode = languageVoiceMap[language] || 'en-US';
    utterance.lang = targetLangCode;

    const voices = window.speechSynthesis.getVoices();
    const matchingVoice = voices.find(v => v.lang === targetLangCode || v.lang.startsWith(language));
    if (matchingVoice) {
      utterance.voice = matchingVoice;
    }

    utterance.rate = 0.95;
    utterance.pitch = 1.0;
    window.speechSynthesis.speak(utterance);
  };

  const toggleTheme = () => {
    setTheme(prev => (prev === 'light' ? 'dark' : 'light'));
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <ThemeContext.Provider value={{
      theme,
      toggleTheme,
      language,
      setLanguage,
      t,
      isRTL: language === 'ar',
      isTtsEnabled,
      toggleTts,
      speakText
    }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};
